# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerator.proto\"\x17\n\x07Network\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"4\n\x04Game\x12\x16\n\x0estart_position\x18\x01 \x01(\t\x12\x14\n\x0cmove_indices\x18\x02 \x03(\x05\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x05\x42\x61tch\x12\x14\n\x05games\x18\x01 \x03(\x0b\x32\x05.Game\"\x1f\n\nLastUpdate\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xa4\x01\n\tGenerator\x12!\n\x0bupload_game\x12\x05.Game\x1a\t.Response\"\x00\x12#\n\x0cupload_batch\x12\x06.Batch\x1a\t.Response\"\x00\x12(\n\x0fget_last_update\x12\x06.Empty\x1a\x0b.LastUpdate\"\x00\x12%\n\x0fget_new_network\x12\x06.Empty\x1a\x08.Network\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETWORK._serialized_start=19
  _NETWORK._serialized_end=42
  _GAME._serialized_start=44
  _GAME._serialized_end=96
  _RESPONSE._serialized_start=98
  _RESPONSE._serialized_end=125
  _BATCH._serialized_start=127
  _BATCH._serialized_end=156
  _LASTUPDATE._serialized_start=158
  _LASTUPDATE._serialized_end=189
  _EMPTY._serialized_start=191
  _EMPTY._serialized_end=198
  _GENERATOR._serialized_start=201
  _GENERATOR._serialized_end=365
# @@protoc_insertion_point(module_scope)
